#ifndef PCAPFS_DHCP_OPTIONS_H
#define PCAPFS_DHCP_OPTIONS_H

#include <string>
#include <set>
#include <vector>

namespace pcapfs {
    namespace dhcpOptions {
        const std::set<uint8_t> typesWithIpAddress = {1, 16, 28, 32, 50, 54}; // 4 byte
        const std::set<uint8_t> typesWithListOfIpAddresses = {3, 4, 5, 6, 7, 8, 9, 10, 11, 21, 33, 41, 42, 44,
                                                            45, 48, 49, 65, 68, 69, 70, 71, 72, 73, 74, 75, 76, 150};
        const std::set<uint8_t> typesWithIntValue = {13, 22, 26, 57}; // 2 byte
        const std::set<uint8_t> typesWithListOfIntValues = {25};
        const std::set<uint8_t> typesWithTimeValue = {2, 24, 35, 38, 51, 58, 59, 91}; // 4 byte
        const std::set<uint8_t> typesWithOneByteValue = {19, 20, 23, 27, 29, 30, 31, 34, 36, 37, 39, 46, 52, 116}; // 1 byte

        const std::vector<std::string> dhcpOptionStrings = {
            "Pad Option",
            "Subnet Mask",
            "Time Offset",
            "Router",
            "Time Servers",
            "Name Servers",
            "DNS Servers",
            "Log Servers",
            "Cookie Servers",
            "LPR Servers",
            "Impress Servers",
            "RLP Servers",
            "Host Name",
            "Boot File Size",
            "Merit Dump File",
            "Domain Name",
            "Swap Server",
            "Root Path",
            "Extension File",
            "IP Layer Forwarding",
            "Src route enabler",
            "Policy Filter",
            "Maximum DG Reassembly Size",
            "Default IP TTL",
            "Path MTU Aging Timeout",
            "MTU Plateau",
            "Interface MTU Size",
            "All Subnets Are Local",
            "Broadcast Address",
            "Perform Mask Discovery",
            "Provide Masks to Others",
            "Perform Router Discovery",
            "Router Solicitation Address",
            "Static Routing Table",
            "Trailer Encapsulation",
            "ARP Cache Timeout",
            "Ethernet Encapsulation",
            "Default TCP Time to Live",
            "TCP Keepalive Interval",
            "TCP Keepalive Garbage",
            "NIS Domain Name",
            "NIS Server Addresses",
            "NTP Server Addresses",
            "Vendor-Specific Information",
            "NETBIOS Name Server",
            "NETBIOS Datagram Distribution",
            "NETBIOS Node Type",
            "NETBIOS Scope",
            "X Window Font Server",
            "X Window Display Manager",
            "Requested IP Address",
            "IP Address Lease Time",
            "Option Overload",
            "DHCP Message Type",
            "DHCP Server Identifier",
            "Parameter Request List",
            "Message",
            "DHCP Maximum Message Size",
            "Renewal Time Value",
            "Rebinding Time Value",
            "Vendor Class Identifier",
            "Client Identifier",
            "Netware/IP Domain Name",
            "Netware/IP sub Options",
            "NIS+ v3 Client Domain Name",
            "NIS+ v3 Server Address",
            "TFTP Server Name",
            "Boot File Name",
            "Home Agent Addresses",
            "Simple Mail Server Addresses",
            "Post Office Server Addresses",
            "Network News Server Addresses",
            "WWW Server Addresses",
            "Finger Server Addresses",
            "Chat Server Addresses",
            "StreetTalk Server Addresses",
            "StreetTalk Directory Assistance Addresses",
            "User Class Information",
            "SLP Directory Agent",
            "SLP Service Scope",
            "Rapid Commit",
            "Client Fully Qualified Domain Name",
            "Agent Information Option",
            "Internet Storage Name Service",
            "Undefined Option",
            "Novell Directory Servers",
            "Novell Directory Server Tree Name",
            "Novell Directory Server Context",
            "BCMCS Controller Domain Name List",
            "BCMCS Controller IPv4 Address List",
            "Authentication",
            "Client Last Transaction Time",
            "Associated IP",
            "Client System",
            "Client Network Device Interface",
            "LDAP Use",
            "Undefined Option",
            "UUID/GUID-based Client Identifier",
            "Open Group's User Authentication",
            "GEOCONF_CIVIC",
            "IEEE 1003.1 TZ String",
            "Reference to the TZ Database",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Autonomous System Number",
            "Undefined Option",
            "Undefined Option",
            "NetInfo Parent Server Address",
            "NetInfo Parent Server Tag",
            "URL",
            "Undefined Option",
            "Auto Configure",
            "Name Service Search",
            "Subnet Selection",
            "DNS Domain Search List",
            "SIP Servers",
            "Classless Static Route",
            "CCC, CableLabs Client Configuration",
            "GeoConf",
            "Vendor-Identifying Vendor Class",
            "Vendor-Identifying Vendor Specific",
            "Undefined Option",
            "Undefined Option",
            "TFTP Server IP Address",
            "Call Server IP Address",
            "Discrimination String",
            "Remote Statistics Server IP Address",
            "802.1Q VLAN ID",
            "802.1Q VLAN Priority",
            "Diffserv Code Point",
            "HTTP Proxy For Phone Applications",
            "OPTION_PANA_AGENT",
            "OPTION_V4_LOST",
            "CAPWAP Access Controller Addresses",
            "A Series Of Suboptions",
            "A Series Of Suboptions",
            "List of domain names to search for SIP User Agent Configuration",
            "ANDSF IPv4 Address",
            "Undefined Option",
            "Geospatial Location with Uncertainty",
            "Forcerenew Nonce Capable",
            "Information for selecting RDNSS",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "TFTP Server Address",
            "Status Code",
            "Base Time",
            "Start Time of State",
            "Query Start Time",
            "Query End Time",
            "DHCP State",
            "Data Source",
            "PCP Servers",
            "Portparams",
            "DHCP Captive-Portal",
            "Manufacturer Usage Descriptions",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Ether Boot",
            "IP Telephone",
            "Ether Boot PacketCable and CableHome",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "pxelinux.magic (string)",
            "pxelinux.configfile (text)",
            "pxelinux.pathprefix (text)",
            "pxelinux.reboottime",
            "OPTION_6RD with N/4 6rd BR addresses",
            "Access Network Domain Name",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Subnet Allocation",
            "Virtual Subnet Allocation",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Undefined Option",
            "Private/Classless Static Route (Microsoft)",
            "Undefined Option",
            "Undefined Option",
            "Private/Proxy Autodiscovery",
            "Undefined Option",
            "Undefined Option",
            "End"
        };
    }
}


#endif // PCAPFS_DHCP_OPTIONS_H
